# Generated by Django 3.2 on 2021-05-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField()),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField()),
                ('file_field', models.FileField(upload_to='user1')),
                ('is_available', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField()),
                ('validity_flag', models.BooleanField(default=True)),
                ('directory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apka.directory')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('last_updated', models.DateTimeField()),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('last_updated', models.DateTimeField()),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField()),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField()),
                ('validity_flag', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=20)),
                ('desc', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('validity_flag', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apka.sectioncategory')),
                ('file_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.file')),
                ('parent_section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apka.filesection')),
                ('status_data_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apka.statusdata')),
                ('status_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apka.status')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='parent_dir',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apka.directory'),
        ),
    ]
