# Generated by Django 3.2 on 2021-05-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='file_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apka.file'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='status_data_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apka.statusdata'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='status_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apka.status'),
        ),
    ]
