# Generated by Django 3.2.1 on 2021-05-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_auto_20210504_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdata',
            name='status_data',
            field=models.TextField(),
        ),
    ]
