# Generated by Django 3.1.7 on 2021-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0005_file_frama_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='validity_flag',
        ),
        migrations.RemoveField(
            model_name='file',
            name='validity_flag',
        ),
        migrations.AlterField(
            model_name='directory',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
