# Generated by Django 3.2.1 on 2021-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0007_auto_20210518_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
