# Generated by Django 3.2.1 on 2021-05-19 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apka', '0009_auto_20210518_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='apka.sectioncategory'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='status_data_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apka.statusdata'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='status_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apka.status'),
        ),
        migrations.AlterField(
            model_name='statusdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
